import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header'
import Topcards from '../components/TopCards'
import BarChart from '../components/BarChart'
import RecentOrder from '../components/RecentOrder'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-zinc-900 min-h-screen">
                <Header />
                <Topcards />
                <div className="grid p-4 md:grid-cols-3 grid-cols-1 gap-4">
                    <BarChart />
                    <RecentOrder />
                </div>
            </main>
        </>
    )
}
